### ISSUE TITLE
bigger jpgs are getting flipped 

### ISSUE THREAD

**Issue by daVid0n** [AdamMoses-GitHub/MMM-ImageSlideshow#15]
I loaded some bigger jpgs and they are being displayed flipped by 180° - I cannot see any logic in this, do you have any advice?
smaller jpgs are being displayed normally.
ty

**Comment by OneOfTheInfiniteMonkeys** [comment]
Hi, I am just another user. I have not seen "bigger" [JPEG](https://en.wikipedia.org/wiki/JPEG)'s being flipped. 

I have seen that the viewer is not respecting the orientation setting of a JPEG (EXIF metadata). I imagine this is not an issue with MMM-ImageSlideshow but with the viewer software MagicMirror­² is using. I currently understand the viewer software to be [electron](https://github.com/electron/electron) .

In practice what this means is that using preview in say Windows file explorer for example. Images are shown as you might expect when viewed (as the EXIF data in the JPEG file is used and Windows file explorer rotates the image for you). When viewed on the RASPI through electron, the image is not rotated as desired as I think electron is ignoring the EXIF metadata. I end up rotating the images before placing them on my RASPI. Here is some [more](https://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/) background.

Keep in mind the JPEG file structure is complex and if you have a sample image showing the "undesirable" behaviour it might assist someone debugging.

Hope this helps.

**Comment by OneOfTheInfiniteMonkeys** [comment]
If I have understood it correctly the root cause is detailed [here](https://github.com/electron/electron/issues/8059).

Hope this helps?

**Comment by daVid0n** [comment]
Hey there,

thank you very much for your response and both links!!
Now, I totally understood, that electron is the issue here.. no wait: I am the issue, of course xD

I executed a manual export of all the images I want to display via ImageSlideshow, then - which also generated the correct exif-data. 
This seems so obvious now.. stupid me.

Great job InfiniteMonkey!
Kindest regards
